# Generated by Django 2.2.5 on 2019-11-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('image_url', models.URLField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
