# Generated by Django 2.2.5 on 2019-11-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0003_auto_20191121_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backendcomment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='backendlike',
            old_name='user',
            new_name='owner',
        ),
    ]
