# Generated by Django 2.2.5 on 2019-11-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0004_auto_20191121_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='backendlike',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='backendproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
