# Generated by Django 2.2.5 on 2019-11-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0008_auto_20191130_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backendproduct',
            name='origin',
        ),
    ]
